name: Cleanup Soft-Deleted Keywords

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger cleanup endpoint
        run: |
          curl -X POST ${{ secrets.PRODUCTION_URL }}/api/cron/cleanup-keywords \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"